trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployInfrastructure
  displayName: 'Deploy Terraform Infrastructure'
  jobs:
  - job: Terraform
    displayName: 'Run Terraform Apply'
    steps:
    - script: |
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Init and Apply'
      env:
        ARM_CLIENT_ID: $(servicePrincipalId)
        ARM_CLIENT_SECRET: $(servicePrincipalKey)
        ARM_SUBSCRIPTION_ID: $(subscriptionId)
        ARM_TENANT_ID: $(tenantId)

- stage: BuildPushAndDeploy
  displayName: 'Build, Push, and Deploy Image'
  dependsOn: DeployInfrastructure
  jobs:
  - job: Docker
    displayName: 'Build, Push and Deploy'
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: 'Docker Reg' # Your Docker Registry service connection

    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        command: 'buildAndPush'
        repository: 'portfolio-site'
        dockerfile: '**/Dockerfile'
        tags: 'latest'

    - task: AzureWebAppContainer@1
      displayName: 'Deploy Container to App Service'
      inputs:
        azureSubscription: 'Dev-Portal' # Your Azure service connection
        appName: 'portfolio-demo'
        imageName: 'portfolioregistrytf020qrb.azurecr.io/portfolio-site:latest'