# This is the full and final pipeline configuration.

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
# STAGE 1: DEPLOY INFRASTRUCTURE
# This stage uses Terraform to build your resources in Azure.
- stage: DeployInfrastructure
  displayName: 'Deploy Terraform Infrastructure'
  jobs:
  - job: Terraform
    displayName: 'Run Terraform Apply'
    steps:
    # Installs Terraform on the build agent
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    # Runs Terraform commands with secure credentials
    - script: |
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Init and Apply'
      env:
        ARM_CLIENT_ID: $(servicePrincipalId)
        ARM_CLIENT_SECRET: $(servicePrincipalKey)
        ARM_SUBSCRIPTION_ID: $(subscriptionId)
        ARM_TENANT_ID: $(tenantId)

# STAGE 2: BUILD, PUSH, AND DEPLOY CONTAINER
# This stage builds your Docker image and deploys it to the Web App.
- stage: BuildPushAndDeploy
  displayName: 'Build, Push, and Deploy Image'
  dependsOn: DeployInfrastructure
  jobs:
  - job: Docker
    displayName: 'Build, Push and Deploy'
    steps:
    # Login to your Azure Container Registry
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: 'Docker Reg' # Your Docker Registry service connection

    # Build the image and push it to your registry
    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        command: 'buildAndPush'
        repository: 'portfolio-site'
        dockerfile: '**/Dockerfile'
        tags: 'latest'

    # Tell the Web App to deploy the new container image
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Container to App Service'
      inputs:
        azureSubscription: 'Dev-Portal' # Your Azure service connection
        appName: 'portfolio-demo'
        imageName: 'portfolioregistrytf020qrb.azurecr.io/portfolio-site:latest'