trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployInfrastructure
  displayName: 'Deploy Terraform Infrastructure'
  jobs:
  - job: Terraform
    displayName: 'Run Terraform Apply'
    steps:

    # Step 1: Install Terraform
    - script: |
        echo "Installing Terraform..."
        wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
        unzip terraform_1.6.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
      displayName: 'Install Terraform'

    # Step 2: Export ARM_* variables and run Terraform
    - script: |
        echo "Exporting Azure credentials..."
        export ARM_CLIENT_ID=$(servicePrincipalId)
        export ARM_CLIENT_SECRET=$(servicePrincipalKey)
        export ARM_SUBSCRIPTION_ID=$(subscriptionId)
        export ARM_TENANT_ID=$(tenantId)

        echo "Initializing Terraform..."
        terraform init

        echo "Applying Terraform..."
        terraform apply -auto-approve
      displayName: 'Terraform Init and Apply'

- stage: BuildPushAndDeploy
  displayName: 'Build, Push, and Deploy Docker Image'
  dependsOn: DeployInfrastructure
  jobs:
  - job: Docker
    displayName: 'Build, Push and Deploy'
    steps:

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: 'Docker Reg' # Replace with your service connection

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: 'buildAndPush'
        repository: 'portfolio-site'
        dockerfile: '**/Dockerfile'
        tags: 'latest'

    - task: AzureWebAppContainer@1
      displayName: 'Deploy Container to App Service'
      inputs:
        azureSubscription: 'Dev-Portal' # Your Azure DevOps service connection
        appName: 'portfolio-demo'
        imageName: 'portfolioregistrytf020qrb.azurecr.io/portfolio-site:latest'
