trigger:
- main   # or your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myapp'

steps:
- task: Docker@2
  displayName: Build and Push Image to ACR
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    containerRegistry: 'Docker Reg'   # MUST match your service connection name exactly
    tags: |
      $(Build.BuildId)
